### PR TITLE
Deprecate py3.8 and deal with action warnings

### PR DESCRIPTION
**Pull request by unkcpz**

### CODE REVIEW

**Comment by danielhollas** [comment]
Why deprecate 3.8? That is still a version in use by older Linux distros I think, let's not make things more complicated for potential users.

**Comment by unkcpz** [comment]
Okay, that is true, I was at this repo on other changes and find this from README https://github.com/aiidalab/aiidalab-launch#compatibility.

**Comment by danielhollas** [comment]
Interesting. TBH I don't really see a reason why this package should follow NEP 29. This package does not depend on the Python scientific ecosystem (numpy et al). On the contrary, since it is a CLI tool, it's likely to be installed system-wide using Linux distribution Python, that is often lagging behind. So I would simply vote for not following NEP 29.

**Comment by unkcpz** [comment]
Yes, agree. I close this PR.

**Pull request closed without merging**
