### PR TITLE
Support create profile with image specified

### PR DESCRIPTION
**Pull request by unkcpz**

### CODE REVIEW

**Comment by danielhollas** [comment]
Suggestion: it would be more generally useful to support creating a profile from a yaml file configuration, similarly to `verdi code create`

**Comment by unkcpz** [comment]
> Suggestion: it would be more generally useful to support creating a profile from a yaml file configuration, similarly to verdi code create

Yes, that'll be convenient. But the feature added in this PR is for the upcoming QeApp tutorial, in the doc it can simply use new `qe` stack to get a QeApp-ready container. (It is exactly what you suggested at https://github.com/aiidalab/aiidalab-docker-stack/pull/381#issuecomment-1563093644) I find it very straightforward to use that for Quantum Mobile.

**Comment by unkcpz** [comment]
Hi @danielhollas, mind having a look at this one? For the config file as input, I did that for the `optimade-launch` which I stole most of the code from here and had conifg file as input. I'll open a similar PR here soon.

**Comment by danielhollas** [comment]
Sure, will take a look tomorrow.

**Review by danielhollas — APPROVED** [review]
Tested locally, LGTM! :rocket:

**Comment by unkcpz** [comment]
@danielhollas thanks!

**Pull request merged**
